config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_complex', to: 'checkout#create_complex', as: 'checkout_create_complex'
    post 'create_building', to: 'checkout#create_building', as: 'checkout_create_building'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  resources :commercial_units
  resources :complex_buildings
  resources :houses
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/commercial_unit.rb
# frozen_string_literal: true

class CommercialUnit < ApplicationRecord
  belongs_to :manager, class_name: 'User', foreign_key: :user_id
  has_one_attached :icon
  validates :price, presence: true, length: { minimum: 3 }
end

app/controllers/commercial_units_controller.rb
# frozen_string_literal: true

class CommercialUnitsController < ApplicationController
  before_action :set_commercial_unit, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /commercial_units or /commercial_units.json
  def index
    @commercial_units = CommercialUnit.all
  end

  # GET /commercial_units/1 or /commercial_units/1.json
  def show; end

  # GET /commercial_units/new
  def new
    @commercial_unit = current_user.commercial_units.build
  end

  # GET /commercial_units/1/edit
  def edit; end

  # POST /commercial_units or /commercial_units.json
  def create
    @commercial_unit = current_user.commercial_units.build(commercial_unit_params)

    respond_to do |format|
      if @commercial_unit.save
        format.html { redirect_to @commercial_unit, notice: 'Commercial unit was successfully created.' }
        format.json { render :show, status: :created, location: @commercial_unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commercial_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commercial_units/1 or /commercial_units/1.json
  def update
    respond_to do |format|
      if @commercial_unit.update(commercial_unit_params)
        format.html { redirect_to @commercial_unit, notice: 'Commercial unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @commercial_unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commercial_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commercial_units/1 or /commercial_units/1.json
  def destroy
    @commercial_unit.destroy
    respond_to do |format|
      format.html { redirect_to commercial_units_url, notice: 'Commercial unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_commercial_unit
    @commercial_unit = CommercialUnit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def commercial_unit_params
    params.require(:commercial_unit).permit(:owner, :address, :shops, :sqmt, :parking, :price, :icon)
  end
end

app/helpers/commercial_units_helper.rb
# frozen_string_literal: true

module CommercialUnitsHelper
end

app/views/commercial_units/_form.html.erb
<%= simple_form_for(@commercial_unit) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <span class='hide'><%= f.input :owner, :input_html => { :value => current_user.name } %></span>
    <%= f.input :address %>
    <%= f.input :shops %>
    <%= f.input :sqmt %>
    <%= f.input :parking %>
        <p>must be at least $100</p>
    <%= f.input :price %>
  </div>
<div><%= f.label :icon, class: 'label' %>
    <%= f.file_field :icon,
                required: true,
                input_html: { autocomplete: "icon" }, direct_upload: true %>
    </div><br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/commercial_units/edit.html.erb
<h1>Editing Commercial Unit</h1>

<%= render 'form', commercial_unit: @commercial_unit %>

<%= link_to 'Show', @commercial_unit %> |
<%= link_to 'Back', commercial_units_path %>

app/views/commercial_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commercial Units</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Shops</th>
      <th>Sqmt</th>
      <th>Parking</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commercial_units.each do |commercial_unit| %>
      <tr>
        <td><%= commercial_unit.owner %></td>
        <td><%= commercial_unit.address %></td>
        <td><%= commercial_unit.shops %></td>
        <td><%= commercial_unit.sqmt %></td>
        <td><%= commercial_unit.parking %></td>
        <td><%= commercial_unit.price %></td>
        <td><%= commercial_unit.user %></td>
        <td><%= link_to 'Show', commercial_unit %></td>
        <td><%= link_to 'Edit', edit_commercial_unit_path(commercial_unit) %></td>
        <td><%= link_to 'Destroy', commercial_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commercial Unit', new_commercial_unit_path %>

app/views/commercial_units/new.html.erb
<h1>New Commercial Unit</h1>

<%= render 'form', commercial_unit: @commercial_unit %>

<%= link_to 'Back', commercial_units_path %>

app/views/commercial_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @commercial_unit.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @commercial_unit.address %>
</p>

<p>
  <strong>Shops:</strong>
  <%= @commercial_unit.shops %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @commercial_unit.sqmt %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @commercial_unit.parking %>
</p>

<p>
  <strong>Price:</strong>
  <%= @commercial_unit.price %>
</p>

<div class='imgh'><%= image_tag(@commercial_unit.icon, class: 'pics') %></div>


<%= link_to 'Edit', edit_commercial_unit_path(@commercial_unit) %> |
<%= link_to 'Back', commercial_units_path %>