config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_complex', to: 'checkout#create_complex', as: 'checkout_create_complex'
    post 'create_building', to: 'checkout#create_building', as: 'checkout_create_building'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  resources :commercial_units
  resources :complex_buildings
  resources :houses
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  before_action :set_house, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1 or /houses/1.json
  def show; end

  # GET /houses/new
  def new
    @house = current_user.houses.build
  end

  # GET /houses/1/edit
  def edit; end

  # POST /houses or /houses.json
  def create
    @house = current_user.houses.build(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_house
    @house = House.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def house_params
    params.require(:house).permit(:owner, :address, :rooms, :sqmt, :floors, :air_condition, :price, :icon)
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= simple_form_for(@house) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <span class='hide'><%= f.input :owner, :input_html => { :value => current_user.name } %></span>
    <%= f.input :address %>
    <%= f.input :rooms %>
    <%= f.input :sqmt %>
    <%= f.input :floors %>
    <%= f.input :air_condition %>
    <p>must be at least $100</p>
    <%= f.input :price %>
  </div>
  <div><%= f.label :icon, class: 'label' %>
    <%= f.file_field :icon,
                required: true,
                input_html: { autocomplete: "icon" }, direct_upload: true %>
    </div><br>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Houses</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Rooms</th>
      <th>Sqmt</th>
      <th>Floors</th>
      <th>Air condition</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.owner %></td>
        <td><%= house.address %></td>
        <td><%= house.rooms %></td>
        <td><%= house.sqmt %></td>
        <td><%= house.floors %></td>
        <td><%= house.air_condition %></td>
        <td><%= house.price %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @house.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @house.address %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @house.rooms %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @house.sqmt %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @house.floors %>
</p>

<p>
  <strong>Air condition:</strong>
  <%= @house.air_condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<div class='imgh'><%= image_tag(@house.icon, class: 'pics') %></div>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>