config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_complex', to: 'checkout#create_complex', as: 'checkout_create_complex'
    post 'create_building', to: 'checkout#create_building', as: 'checkout_create_building'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  resources :commercial_units
  resources :complex_buildings
  resources :houses
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/complex_building.rb
# frozen_string_literal: true

class ComplexBuilding < ApplicationRecord
  belongs_to :manager, class_name: 'User', foreign_key: :user_id
  has_one_attached :icon
  validates :price, presence: true, length: { minimum: 3 }
end

app/controllers/complex_buildings_controller.rb
# frozen_string_literal: true

class ComplexBuildingsController < ApplicationController
  before_action :set_complex_building, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /complex_buildings or /complex_buildings.json
  def index
    @complex_buildings = ComplexBuilding.all
  end

  # GET /complex_buildings/1 or /complex_buildings/1.json
  def show; end

  # GET /complex_buildings/new
  def new
    @complex_building = current_user.complex_buildings.build
  end

  # GET /complex_buildings/1/edit
  def edit; end

  # POST /complex_buildings or /complex_buildings.json
  def create
    @complex_building = current_user.complex_buildings.build(complex_building_params)

    respond_to do |format|
      if @complex_building.save
        format.html { redirect_to @complex_building, notice: 'Complex building was successfully created.' }
        format.json { render :show, status: :created, location: @complex_building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @complex_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complex_buildings/1 or /complex_buildings/1.json
  def update
    respond_to do |format|
      if @complex_building.update(complex_building_params)
        format.html { redirect_to @complex_building, notice: 'Complex building was successfully updated.' }
        format.json { render :show, status: :ok, location: @complex_building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @complex_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complex_buildings/1 or /complex_buildings/1.json
  def destroy
    @complex_building.destroy
    respond_to do |format|
      format.html { redirect_to complex_buildings_url, notice: 'Complex building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_complex_building
    @complex_building = ComplexBuilding.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def complex_building_params
    params.require(:complex_building).permit(:owner, :address, :units, :sqmt, :price, :icon)
  end
end

app/helpers/complex_buildings_helper.rb
# frozen_string_literal: true

module ComplexBuildingsHelper
end

app/views/complex_buildings/_form.html.erb
<%= simple_form_for(@complex_building) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <span class='hide'><%= f.input :owner, :input_html => { :value => current_user.name } %></span>
    <%= f.input :address %>
    <%= f.input :units %>
    <%= f.input :sqmt %>
        <p>must be at least $100</p>
    <%= f.input :price %>
  </div>
  <div><%= f.label :icon, class: 'label' %>
    <%= f.file_field :icon,
                required: true,
                input_html: { autocomplete: "icon" }, direct_upload: true %>
    </div><br>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/complex_buildings/edit.html.erb
<h1>Editing Complex Building</h1>

<%= render 'form', complex_building: @complex_building %>

<%= link_to 'Show', @complex_building %> |
<%= link_to 'Back', complex_buildings_path %>

app/views/complex_buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complex Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Units</th>
      <th>Sqmt</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complex_buildings.each do |complex_building| %>
      <tr>
        <td><%= complex_building.owner %></td>
        <td><%= complex_building.address %></td>
        <td><%= complex_building.units %></td>
        <td><%= complex_building.sqmt %></td>
        <td><%= complex_building.price %></td>
        <td><%= link_to 'Show', complex_building %></td>
        <td><%= link_to 'Edit', edit_complex_building_path(complex_building) %></td>
        <td><%= link_to 'Destroy', complex_building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complex Building', new_complex_building_path %>

app/views/complex_buildings/new.html.erb
<h1>New Complex Building</h1>

<%= render 'form', complex_building: @complex_building %>

<%= link_to 'Back', complex_buildings_path %>

app/views/complex_buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @complex_building.owner %>
</p>

<p>
  <strong>Address:</strong>
  <%= @complex_building.address %>
</p>

<p>
  <strong>Units:</strong>
  <%= @complex_building.units %>
</p>

<p>
  <strong>Sqmt:</strong>
  <%= @complex_building.sqmt %>
</p>

<p>
  <strong>Price: </strong>
  $<%= @complex_building.price %>
</p>

<%= link_to 'Edit', edit_complex_building_path(@complex_building) %> |
<%= link_to 'Back', complex_buildings_path %>