config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    post 'create_complex', to: 'checkout#create_complex', as: 'checkout_create_complex'
    post 'create_building', to: 'checkout#create_building', as: 'checkout_create_building'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  resources :commercial_units
  resources :complex_buildings
  resources :houses
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @houses = House.all
    @commercial_units = CommercialUnit.all
    @complex_buildings = ComplexBuilding.all
  end
end

app/views/home/index.html.erb
<div class='alignment'>
  <div class='houses'>
    <% @houses.each do |house| %>
    <br>
    <p>Category: House</p>
    <p> Owner <%= house.owner%></p>
    <p> floors <%= house.floors%></p>
    <p> Price $<%= house.price %></p>
    <p> Rooms <%= house.rooms%></p>
    <div class='imgh'><%= image_tag(house.icon, class: 'bigpics') %></div>
    <br>
    <%= button_to 'Buy Now', checkout_create_path, method: :post, params: { id: house.id }, remote: true, class: 'button is-info is-clickable' %>
    <% end %>
  </div>
  <div class='houses'>
    <br>
    <% @commercial_units.each do |unit| %>
    <p>Category: commercial units</p>
    <p> Owner <%= unit.owner%></p>
    <p> shops <%= unit.shops%></p>
    <p> Price $<%= unit.price%></p>
    <p> Rooms <%= unit.parking%></p>
    <div class='imgh'><%= image_tag(unit.icon, class: 'bigpics') %></div>
    <br>
    <%= button_to 'Buy Now', checkout_create_building_path, method: :post, params: { id: unit.id }, remote: true, class: 'button is-info is-clickable' %>
    <% end %>
  </div>
  <div class='houses'>
    <br>
    <% @complex_buildings.each do |building| %>
    <p>Category: Complex building</p>
    <p> Owner <%= building.owner%></p>
    <p> Units <%= building.units%></p>
    <p> Price $<%= building.price%></p>
    <p> Square meter <%= building.sqmt%></p>
    <div class='imgh'><%= image_tag(building.icon, class: 'bigpics') %></div>
    <br>
    <%= button_to 'Buy Now', checkout_create_complex_path, method: :post, params: { id: building.id }, remote: true, class: 'button is-info is-clickable' %>
    <% end %>
  </div>
</div>